development: &sqlite
  database: db/development.sqlite3
  adapter: sqlite3
  pool: 5
  timeout: 5000

test: &test
  <<: *sqlite
  database: db/test.sqlite3

production:
  adapter: postgresql
  encoding: unicode
  database: genie
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: 5
  timeout: 5000
