development: &sqlite
  database: db/development.sqlite3
  adapter: sqlite3
  pool: 5
  timeout: 5000

test: &test
  <<: *sqlite
  database: db/test.sqlite3

cucumber:
  <<: *test

<% glob = File.join Rails.application.root, 'config', 'database.d', '*.yml' %>
<%= Dir[glob].reduce('') { |memo, inc| memo += IO.read(inc) + "\n" } %>
