development: &sqlite
  database: db/development.sqlite3
  adapter: sqlite3
  pool: 5
  timeout: 5000

test: &test
  <<: *sqlite
  database: db/test.sqlite3

cucumber:
  <<: *test

production:
  adapter: postgresql
  encoding: unicode
  database: genie
  username: <%= Rails.application.config.postgresql[:username] %>
  password: <%= Rails.application.config.postgresql[:password] %>
  pool: 5
  timeout: 5000
