development: &sqlite
  database: db/development.sqlite3
  adapter: sqlite3
  pool: 5
  timeout: 5000

test: &test
  <<: *sqlite
  database: db/test.sqlite3

production:
  adapter: mysql2
  encoding: utf8
  database: genie
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
